export const works = [
  {
    id: 1,
    image: "img/Ecommerce-website.PNG",
    title: "TopApparel",
    type: "(Desktop First)",
    description: "Sample Ecommerce Website",
    link: "https://jp-ce.github.io/Ecommerce/",
  },
  {
    id: 2,
    image: "img/travel-website.PNG",
    title: "Philippines",
    type: "(Desktop First)",
    description: "Sample Travel Website",
    link: "https://jp-ce.github.io/Travel-Website/",
  },
  {
    id: 3,
    image: "img/fitnesswebsite.PNG",
    title: "FinleyFitness",
    type: "(Desktop First)",
    description: "Sample Fitness Website",
    link: "https://jp-ce.github.io/Fitness-Program-Website/",
  },
  {
    id: 4,
    image: "img/web4.jpg",
    title: "Coming soon!",
    type: "(ANY)",
    description: "Not yet available",
    link: "img/web4.jpg",
  },
  {
    id: 5,
    image: "img/web5.jpg",
    title: "Coming soon!",
    type: "(ANY)",
    description: "Not yet available",
    link: "img/web5.jpg",
  },
  {
    id: 6,
    image: "img/web6.jpg",
    title: "Coming soon!",
    type: "(ANY)",
    description: "Not yet available",
    link: "img/web6.jpg",
  },
];
