export const works = [
  {
    id: "work-showcase-1",
    image: "img/miniTube.PNG",
    title: "MiniTube",
    type: "(Desktop First)",
    description: "React App - youtube miniature",
    link: "https://mini-tube.netlify.app/",
    webTechnologies: [
      "HTML & CSS",
      "JavaScript",
      "React.js",
      "API",
      "SASS",
      "Responsive",
      "UI/UX",
    ],
    about: [
      "A miniature version of the ever popular video sharing platform - YouTube.  This is a single-paged application project to solidify my understanding on the React.js library. This application makes use of the public YouTube API to display videos based on the search term.",
      "Its main functionalities are: to display and watch YouTube videos, show related videos based on the video clicked, ability to favourite any chosen videos (using local storage) as well as record the viewing history of the user.",
      "Uses hooks and Context API for state management, react-icons for presentation purposes, axios library for fetching data and react-router-dom library for routing",
    ],
    repoLink: "https://github.com/jp-ce/minitube",
  },
  {
    id: "work-showcase-2",
    image: "img/AnimeCatalogue.PNG",
    title: "AnimeCatalogue",
    type: "(Desktop First)",
    description: "React Application",
    link: "https://anime-catalogue.netlify.app/",
    webTechnologies: [
      "HTML & CSS",
      "JavaScript",
      "React.js",
      "API",
      "SASS",
      "Responsive",
      "UI/UX",
    ],
    about: [
      "This is a pocket catalogue for Anime where a user can search an anime, view its details, and bookmark them.  This application uses the Jikan API which is the unofficial MyAnimeList API.  The API itself is completely public and does not require OAuth from the user.  The get request/anime lookup from the API does not have a daily limit, so the user does not have to worry about going over any daily quotas for fetching data.",
      "This project demonstrates the effectiveness of a single-paged application, showing the fast nature of React.js.  React-router-dom library is used for routing and hooks and Context API for state management.",
    ],
    repoLink: "https://github.com/jp-ce/AnimeCatalogue",
  },
  {
    id: "work-showcase-3",
    image: "img/weatherwatcher.PNG",
    title: "WeatherWatch",
    type: "(Desktop First)",
    description: "Simple React Weather Application",
    link: "https://weatherwatcher.netlify.app/",
    webTechnologies: [
      "HTML & CSS",
      "JavaScript",
      "React.js",
      "API",
      "SASS",
      "Responsive",
      "UI/UX",
    ],
    about: [
      "A simple yet an attractive weather app.  Search any city in the world and find out its current temperature! Or search for your city and find out whether if it is a day for a jacket or a t-shirt",
      "This app uses the OpenWeatherMap API to display current weather conditions based on a search term, in this case a city or a country.",
    ],
    repoLink: "https://github.com/jp-ce/WeatherWatch",
  },
  {
    id: "work-showcase-4",
    image: "img/Ecommerce-website.PNG",
    title: "TopApparel",
    type: "(Desktop First)",
    description: "Sample Ecommerce Website",
    link: "https://jp-ce.github.io/Ecommerce/",
    webTechnologies: [
      "HTML & CSS",
      "JavaScript",
      "SASS",
      "Responsive",
      "UI/UX",
    ],
    about: [
      "This is a mock-up Ecommerce website to practise as well as demonstrate my keen eye for detail and design.  This application contains 4 pages: homepage, login/sign-up, cart as well as a product page.  ",
      "Since this is a mock-up, the functionalities of the usual deployed ecommerce are not demonstrated here.  However, this website is set so that if I decide to incorporate API’s, backend languages and a database, it will function like a normal ecommerce would, so the potential is there.  ",
      "Nevertheless, this website is fully responsive to any device.",
    ],
    repoLink: "https://github.com/jp-ce/Ecommerce",
  },
  {
    id: "work-showcase-5",
    image: "img/travel-website.PNG",
    title: "Philippines",
    type: "(Desktop First)",
    description: "Sample Travel Website",
    link: "https://jp-ce.github.io/Travel-Website/",
    webTechnologies: [
      "HTML & CSS",
      "JavaScript",
      "SASS",
      "Responsive",
      "UI/UX",
    ],
    about: [
      "A mock-up travel website.  Includes a landing page, about, showcase of possible destinations, testimonials, as well as a contact page.",
    ],
    repoLink: "https://github.com/jp-ce/Travel-Website",
  },
  {
    id: "work-showcase-6",
    image: "img/fitnesswebsite.PNG",
    title: "FinleyFitness",
    type: "(Desktop First)",
    description: "Sample Fitness Website",
    link: "https://jp-ce.github.io/Fitness-Program-Website/",
    webTechnologies: ["HTML & CSS", "JavaScript", "SASS"],
    about: [
      "A mock-up fitness website.  Includes a landing page, about, features, testimonials, as well as a contact page.",
    ],
    repoLink: "https://github.com/jp-ce/Fitness-Program-Website",
  },
];
